version: '3.8'

services:
  app:
    image: app
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      SERVER_ENV: ${SERVER_ENV}
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  app-db:
    external: true